services:
  jekyll:
    image: jekyll/minimal:3.8
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4249:4000
    volumes:
      - ./docs:/srv/jekyll
  httpd:
    image: httpd:2.4
    ports:
      - 4250:80
    volumes:
      - ./docs/_site:/usr/local/apache2/htdocs/staticauth-quickstart
